### ISSUE TITLE
Can u pwese updweate da hweb shweigt to b wimter sheeamed???

### ISSUE THREAD

**Issue by Hardwaregore** [TechDudie/GrassBandits#4]
@TechDudie.@TechDudie...........@TechDudie.@TechDudie
............@TechDudie....................@TechDudie..............@TechDudie
............@TechDudie....................@TechDudie.................@TechDudie
............@TechDudie....................@TechDudie..................@TechDudie
............@TechDudie....................@TechDudie................@TechDudie
............@TechDudie....................@TechDudie.@TechDudie

**Comment by TechDudie** [comment]
I gotta credit u on that, that is cool
And sure later

**Comment by Hardwaregore** [comment]
thx...
